language: java
# per https://docs.travis-ci.com/user/languages/java
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
script:
  - ./gradlew check --info
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
